---
name: test
bindings:
  net0:
    type: proxy
    kind: server
    routes:
      - exit: app0
        when:
          - transport: stream
            family: inet6
            destination:
              port: 443
