#!/bin/sh
cd "${0%/*}"
exec .zpm/image/bin/java --add-opens java.base/sun.nio.ch=org.agrona.core $JAVA_OPTIONS -m io.aklivity.zilla.runtime.command/io.aklivity.zilla.runtime.command.internal.ZillaMain "$@"
