name: ${NAMESPACE:-zilla-http-telemetry-attributes}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-develop-SNAPSHOT}
    restart: unless-stopped
    hostname: zilla.examples.dev
    ports:
      - 7114:7114
      - 7190:7190
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/7114"]
    environment:
      ZILLA_INCUBATOR_ENABLED: "true"
    volumes:
      - ./etc:/etc/zilla
    command: start -v -e

networks:
  default:
    driver: bridge
