name: ${NAMESPACE:-zilla-http-proxy-jwt}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-latest}
    restart: unless-stopped
    hostname: zilla.examples.dev
    ports:
      - 7114:7114
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/7114"]
    volumes:
      - ./etc:/etc/zilla
    command: start -v -e

  jwt-cli:
    image: bitnami/jwt-cli
    stdin_open: true
    tty: true
    profiles:
      - on-demand
    volumes:
      - ./private.pem:/private.pem

networks:
  default:
    driver: bridge
