---
name: test
vaults:
    client:
        type: filesystem
        options:
            trust:
                store: stores/client/trust
                type: pkcs12
                password: generated
bindings:
    app0:
        type: tls
        kind: client
        vault: client
        options:
            trust:
                - serverca
            alpn:
                - protocol2
                - null
        exit: net0
