---
name: test
vaults:
    client:
        type: filesystem
        options:
            trust:
                store: stores/client/trust
                type: pkcs12
                password: generated
            keys:
                store: stores/client/keys
                type: pkcs12
                password: generated
bindings:
    app0:
        type: tls
        kind: client
        vault: client
        options:
            trust:
                - serverca
            keys:
                - client1
        exit: net0
