---
name: test
vaults:
    server:
        type: filesystem
        options:
            signers:
                store: stores/server/signers
                type: pkcs12
                password: generated
bindings:
    net0:
        type: tls
        kind: server
        vault: server
        options:
            signers:
                - serverca
        exit: app0
