---
name: test
vaults:
    server:
        type: filesystem
        options:
            keys:
                store: stores/server/keys
                type: pkcs12
                password: generated
            trust:
                store: stores/server/trust
                type: pkcs12
                password: generated
realms:
    - name: clients
      type: tls
bindings:
    net0:
        type: tls
        kind: server
        vault: server
        options:
            keys:
                - localhost
            trust:
                - clientca
            realm: clients
        routes:
            - exit: app0
              allow:
                  realm: clients
                  identity: client#1
