#
# Copyright 2021-2023 Aklivity Inc
#
# Licensed under the Aklivity Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
#   https://www.aklivity.io/aklivity-community-license/
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#

---
name: test
telemetry:
    exporters:
        stdout0:
            type: stdout
guards:
    test0:
        type: test
        options:
            credentials: TOKEN
            lifetime: PT5S
            challenge: PT5S
bindings:
    net0:
        type: http
        kind: server
        options:
            versions:
                - http/1.1
            authorization:
                test0:
                    credentials:
                        cookies:
                            access_token: "{credentials}"
                        headers:
                            authorization: Bearer {credentials}
                        query:
                            access_token: "{credentials}"
        routes:
            - exit: app0
              guarded:
                  test0: []
