#
# Copyright 2021-2023 Aklivity Inc
#
# Licensed under the Aklivity Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
#   https://www.aklivity.io/aklivity-community-license/
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#

---
name: test
telemetry:
  exporters:
    stdout0:
      type: stdout
catalogs:
  catalog0:
    type: schema-registry
    options:
      url: http://localhost:8081
      context: default
      max-age: 30
bindings:
  net0:
    type: http
    kind: server
    options:
      requests:
        - path: /hello
          method: GET
          content:
            model: test
            length: 13
        - path: /valid/{category}/{id}
          method: POST
          content-type:
            - text/plain
          headers:
            code:
              model: test
              length: 13
          params:
            path:
              category:
                model: test
                length: 13
              id:
                model: test
                length: 13
            query:
              page:
                model: test
                length: 13
          content:
            model: json
            catalog:
              catalog0:
                - subject: item
      versions:
        - http/1.1
    routes:
      - exit: app0
        when:
          - headers:
              :authority: localhost:8080
