version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:develop-SNAPSHOT"
    hostname: "zilla"
    command: [ "start", "-v", "-e" ]
    volumes:
      - ./conf:/etc/zilla:ro
    networks:
      - net0
    environment:
      - KEYSTORE_PASSWORD=generated 
    ports:
      - "1883:1883"
      - "8883:8883"
