replicaCount: 1

image:
  repository: ghcr.io/aklivity/zilla
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

livenessProbePort: 0
readinessProbePort: 0

configPath: /etc/zilla
configMaps: {}
secrets: {}

service:
  type: ClusterIP
  ports: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

zilla.yaml: |
  name: example
