---
name: test
bindings:
  sse0:
    type: sse-kafka
    kind: proxy
    routes:
      - exit: kafka0
        when:
          - path: /test
        with:
          topic: test
          event:
            id: '["${base64(key)}","${etag}"]'
