---
name: test
bindings:
    app0:
        type: tcp
        kind: client
        options:
            host: google.com
            port: 8080
        routes:
            - when:
                  - cidr: ::1/64
