---
name: test
bindings:
    net0:
        type: tcp
        kind: server
        options:
            host: 0.0.0.0
            port:
                - 8080
                - 8081
                - 8082-8083
        exit: app0
