/*
 * Copyright 2021-2024 Aklivity Inc
 *
 * Licensed under the Aklivity Community License (the "License"); you may not use
 * this file except in compliance with the License.  You may obtain a copy of the
 * License at
 *
 *   https://www.aklivity.io/aklivity-community-license/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */
package io.aklivity.zilla.runtime.common.avro;

import static io.aklivity.zilla.runtime.common.avro.AvroSink.Delivery.SEGMENTABLE;
import static io.aklivity.zilla.runtime.common.avro.AvroSink.Delivery.STRUCTURED;
import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.ByteBuffer;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

import org.apache.avro.Schema;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericDatumReader;
import org.apache.avro.generic.GenericDatumWriter;
import org.apache.avro.io.BinaryDecoder;
import org.apache.avro.io.BinaryEncoder;
import org.apache.avro.io.DecoderFactory;
import org.apache.avro.io.EncoderFactory;
import org.junit.jupiter.api.Test;

/**
 * Conformance test for the {@code common-avro} codec, oracled by the reference Apache Avro library
 * (test scope only) at the raw single-object datum layer. Authoritative datum bytes come from two
 * sources: checked-in golden fixtures under {@code conformance/<scenario>/} (each an exploded Object
 * Container File covering one feature, regenerated by {@link AvroInteroperabilityTest}), and 500 random
 * values over the cross-language {@code interop.avsc} schema (full type system, recursive record).
 * <p>
 * For each datum the structured pipeline ({@code parse -> validate -> generate}) is compared against the
 * input by decoding both through the same reference reader (value equality, agnostic to block framing),
 * and the segmentable pipeline must reproduce the input bytes verbatim.
 */
public class AvroConformanceTest
{
    private static final String[] SCENARIOS =
    {
        "primitives",
        "array",
        "map",
        "enum",
        "fixed",
        "union",
        "recursive"
    };

    @Test
    public void shouldConformToGoldenScenarioDatums()
    {
        for (String scenario : SCENARIOS)
        {
            assertEquals("null", resource("conformance/" + scenario + "/avro.codec").trim(), scenario + " codec");

            String schemaText = resource("conformance/" + scenario + "/avro.schema");
            byte[] datum = resourceBytes("conformance/" + scenario + "/datum.bin");

            Schema reference = new Schema.Parser().parse(schemaText);
            AvroSchema schema = Avro.schema(schemaText);

            assertEquals(referenceDecode(reference, datum),
                referenceDecode(reference, AvroValues.transcode(schema, datum, STRUCTURED)), scenario);
            assertArrayEquals(datum, AvroValues.transcode(schema, datum, SEGMENTABLE), scenario + " segmented");
        }
    }

    @Test
    public void shouldConformToInteropSchemaAcrossRandomValues()
    {
        String schemaText = resource("interop.avsc");
        Schema reference = new Schema.Parser().parse(schemaText);
        AvroSchema schema = Avro.schema(schemaText);

        Random random = new Random(42L);
        for (int i = 0; i < 500; i++)
        {
            Object value = randomValue(reference, random, 5);
            byte[] datum = referenceEncode(reference, value);

            assertEquals(referenceDecode(reference, datum),
                referenceDecode(reference, AvroValues.transcode(schema, datum, STRUCTURED)), "iteration " + i);
            assertArrayEquals(datum, AvroValues.transcode(schema, datum, SEGMENTABLE), "iteration " + i + " segmented");
        }
    }

    private byte[] referenceEncode(
        Schema schema,
        Object value)
    {
        byte[] bytes;
        try
        {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            BinaryEncoder encoder = EncoderFactory.get().binaryEncoder(out, null);
            GenericDatumWriter<Object> writer = new GenericDatumWriter<>(schema);
            writer.write(value, encoder);
            encoder.flush();
            bytes = out.toByteArray();
        }
        catch (IOException ex)
        {
            throw new UncheckedIOException(ex);
        }
        return bytes;
    }

    private Object referenceDecode(
        Schema schema,
        byte[] binary)
    {
        Object value;
        try
        {
            BinaryDecoder decoder = DecoderFactory.get().binaryDecoder(binary, null);
            GenericDatumReader<Object> reader = new GenericDatumReader<>(schema);
            value = reader.read(null, decoder);
        }
        catch (IOException ex)
        {
            throw new UncheckedIOException(ex);
        }
        return value;
    }

    private String resource(
        String name)
    {
        return new String(resourceBytes(name), UTF_8);
    }

    private byte[] resourceBytes(
        String name)
    {
        byte[] bytes;
        try (InputStream in = getClass().getResourceAsStream(name))
        {
            bytes = in.readAllBytes();
        }
        catch (IOException ex)
        {
            throw new UncheckedIOException(ex);
        }
        return bytes;
    }

    private Object randomValue(
        Schema type,
        Random random,
        int depth)
    {
        Object value;
        switch (type.getType())
        {
        case RECORD:
            GenericData.Record record = new GenericData.Record(type);
            for (Schema.Field field : type.getFields())
            {
                record.put(field.name(), randomValue(field.schema(), random, depth));
            }
            value = record;
            break;
        case ENUM:
            List<String> symbols = type.getEnumSymbols();
            value = new GenericData.EnumSymbol(type, symbols.get(random.nextInt(symbols.size())));
            break;
        case ARRAY:
            int items = depth <= 0 ? 0 : random.nextInt(4);
            GenericData.Array<Object> array = new GenericData.Array<>(items, type);
            for (int i = 0; i < items; i++)
            {
                array.add(randomValue(type.getElementType(), random, depth - 1));
            }
            value = array;
            break;
        case MAP:
            int entries = depth <= 0 ? 0 : random.nextInt(4);
            Map<String, Object> map = new LinkedHashMap<>();
            for (int i = 0; i < entries; i++)
            {
                map.put("k" + i, randomValue(type.getValueType(), random, depth - 1));
            }
            value = map;
            break;
        case UNION:
            List<Schema> branches = type.getTypes();
            value = randomValue(branches.get(random.nextInt(branches.size())), random, depth - 1);
            break;
        case FIXED:
            byte[] fixed = new byte[type.getFixedSize()];
            random.nextBytes(fixed);
            value = new GenericData.Fixed(type, fixed);
            break;
        case BYTES:
            byte[] bytes = new byte[random.nextInt(8)];
            random.nextBytes(bytes);
            value = ByteBuffer.wrap(bytes);
            break;
        case STRING:
            value = randomString(random);
            break;
        case INT:
            value = random.nextInt();
            break;
        case LONG:
            value = random.nextLong();
            break;
        case FLOAT:
            value = random.nextFloat();
            break;
        case DOUBLE:
            value = random.nextDouble();
            break;
        case BOOLEAN:
            value = random.nextBoolean();
            break;
        default:
            value = null;
            break;
        }
        return value;
    }

    private String randomString(
        Random random)
    {
        int length = random.nextInt(8);
        StringBuilder builder = new StringBuilder(length);
        for (int i = 0; i < length; i++)
        {
            builder.append((char) ('a' + random.nextInt(26)));
        }
        return builder.toString();
    }
}
