extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated
  - name: ZILLA_INCUBATOR_ENABLED
    value: "true"

livenessProbePort: 7153
readinessProbePort: 7153

service:
  ports:
    - port: 7153
      name: https
