---
name: test
bindings:
  net0:
    type: http
    kind: server
    options:
      versions:
        - h2
      access-control:
        policy: cross-origin
    routes:
      - exit: app0
        when:
          - headers:
              :scheme: https
              :authority: example.com:9090
