---
name: test
bindings:
  net0:
    type: http
    kind: server
    options:
      versions:
        - h2
    routes:
      - exit: app0
        when:
          - headers:
              :path: /api/*
