name: ${NAMESPACE:-zilla-http-filesystem}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-1}
    restart: unless-stopped
    hostname: zilla.examples.dev
    ports:
      - 7114:7114
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 15s
      test: ["CMD", "sh", "-c", "test -f /var/run/zilla/ready"]
    environment:
      ZILLA_INCUBATOR_ENABLED: "true"
    volumes:
      - ./etc:/etc/zilla
      - ./www:/var/www
    command: start -v -e

networks:
  default:
    driver: bridge
