version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:latest"
    hostname: "zilla"
    command: [ "start", "-v", "-e" ]
    volumes:
      - ./conf:/etc/zilla:ro
      - ./web:/var/www:ro
    networks:
      - net0
    environment:
      - KEYSTORE_PASSWORD=generated
    ports:
      - "8080:8080"
      - "9090:9090"
