version: '3'
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION}
    container_name: zilla
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
    environment:
      ZILLA_INCUBATOR_ENABLED: true
    volumes:
      - ../../specs/petstore.yaml:/etc/zilla/petstore.yaml
      - ../../zilla.yaml:/etc/zilla/zilla.yaml
    command: start -v -e

  openapi-mock:
    image: jormaechea/open-api-mocker
    platform: linux/amd64
    volumes:
      - ../../specs:/app
    ports:
      - "8000:5000"
    command: open-api-mocker -s /app/petstore.yaml

networks:
  default:
    driver: bridge
