extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated
  - name: ZILLA_INCUBATOR_ENABLED
    value: "true"

livenessProbePort: 7171
readinessProbePort: 7171

service:
  ports:
    - port: 7171
      name: amqps
    - port: 7172
      name: amqp
