image:
  tag: develop-SNAPSHOT

extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated

livenessProbePort: 7171
readinessProbePort: 7171

service:
  ports:
    - port: 7171
      name: amqps
    - port: 7172
      name: amqp
