#
# Copyright 2021-2024 Aklivity Inc.
#
# Aklivity licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

---
name: test
catalogs:
  catalog0:
    type: test
    options:
      id: 1
      subject: petstore
      schema: |
        asyncapi: 3.0.0
        info:
          title: AsyncAPI Petstore
          license:
            name: MIT
          version: 1.0.0
        servers:
          plain:
            host: localhost:8080
            protocol: http
            protocolVersion: '1.1'
        defaultContentType: application/json
        
        channels:
          pets:
            address: /pets
            messages:
              pet:
                $ref: '#/components/messages/pet'
          showPetById:
            address: /pets/{id}
            messages:
              pet:
                $ref: '#/components/messages/pet'
        
        operations:
          createPets:
            action: send
            bindings:
              http:
                method: POST
              x-zilla-http-kafka:
                overrides:
                  zilla:command: CreatePet
                  zilla:identity: "{identity}"
            channel:
              $ref: '#/channels/pets'
          listPets:
            action: receive
            bindings:
              http:
                method: GET
            channel:
              $ref: '#/channels/pets'
          getPets:
            action: receive
            bindings:
              http:
                method: GET
                query:
                  type: object
                  properties:
                    limit:
                      type: number
            channel:
              $ref: '#/channels/showPetById'
        
        components:
          schemas:
            petPayload:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 0
                  description: Pet id.
                name:
                  type: string
                  description: Pet name.
                tag:
                  type: string
                  description: Tag.
          messages:
            pet:
              name: Pet
              title: Pet
              summary: >-
                Inform about Pet.
              contentType: application/json
              payload:
                $ref: '#/components/schemas/petPayload'

  catalog1:
    type: test
    options:
      id: 7
      subject: petstore
      schema: |
        asyncapi: 3.0.0
        info:
          title: Petstore Kafka API
          version: 1.0.0
        defaultContentType: application/json
        servers:
          host-connections:
            host: 'localhost:9092'
            protocol: kafka-secure
            description: Test broker
            tags:
              - name: 'kind:remote'
                description: This server is a remote server. Not exposed by the application.
              - name: 'visibility:private'
                description: This resource is private and only available to certain users.
        channels:
          petstore:
            address: 'petstore'
            messages:
              pet:
                $ref: '#/components/messages/pet'
            description: The topic on which pet values may be produced and consumed.
        operations:
          listPets:
            action: receive
            channel:
              $ref: '#/channels/petstore'
            summary: >-
              List all pets.
            traits:
              - $ref: '#/components/operationTraits/kafka'
            messages:
              - $ref: '#/channels/petstore/messages/pet'
          createPets:
            action: send
            channel:
              $ref: '#/channels/petstore'
            summary: >-
              Create a pet.
            traits:
              - $ref: '#/components/operationTraits/kafka'
            messages:
              - $ref: '#/channels/petstore/messages/pet'
        components:
          messages:
            pet:
              name: Pet
              title: Pet
              summary: >-
                Inform about Pet.
              contentType: application/json
              traits:
                - $ref: '#/components/messageTraits/commonHeaders'
              payload:
                $ref: '#/components/schemas/petPayload'
          schemas:
            petPayload:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 0
                  description: Pet id.
                name:
                  type: string
                  description: Pet name.
                tag:
                  type: string
                  description: Tag.
          messageTraits:
            commonHeaders:
              headers:
                type: object
                properties:
                  my-app-header:
                    type: integer
                    minimum: 0
                    maximum: 100
          operationTraits:
            kafka:
              bindings:
                kafka:
                  clientId:
                    type: string
                    enum:
                      - my-app-id
bindings:
  asyncapi_proxy0:
    type: asyncapi
    kind: proxy
    options:
      specs:
        http_api:
          catalog:
            catalog0:
              subject: petstore
              version: latest
        kafka_api:
          catalog:
            catalog1:
              subject: petstore
              version: latest
    routes:
      - when:
          - api-id: http_api
        exit: asyncapi_kafka0
        with:
          api-id: kafka_api
