#
# Copyright 2021-2023 Aklivity Inc.
#
# Aklivity licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

---
name: test
catalogs:
  catalog0:
    type: test
    options:
      id: 1
      subject: petstore
      schema: |
        asyncapi: 3.0.0
        info:
          title: AsyncAPI Petstore
          license:
            name: MIT
          version: 1.0.0
        servers:
          plain:
            host: localhost:8080
            protocol: http
            protocolVersion: '2.0'
        defaultContentType: application/json
        
        channels:
          pets:
            address: /pets
            messages:
              pet:
                $ref: '#/components/messages/pet'
          showPetById:
            address: /pets/{id}
            messages:
              pet:
                $ref: '#/components/messages/pet'
        
        operations:
          createPet:
            action: send
            bindings:
              http:
                method: POST
            channel:
              $ref: '#/channels/pets'
          listPets:
            action: receive
            bindings:
              http:
                method: GET
            channel:
              $ref: '#/channels/pets'
          getPets:
            action: receive
            bindings:
              http:
                method: GET
                query:
                  type: object
                  properties:
                    limit:
                      type: number
            channel:
              $ref: '#/channels/showPetById'
        
        components:
          correlationIds:
            petsCorrelationId:
              location: '$message.header#/CorrelId'
          schemas:
            petPayload:
              type: object
              properties:
                id:
                  type: integer
                  minimum: 0
                  description: Pet id.
                name:
                  type: string
                  description: Pet name.
                tag:
                  type: string
                  description: Tag.
          messages:
            pet:
              name: Pet
              title: Pet
              summary: >-
                Inform about Pet.
              contentType: application/json
              correlationId:
                $ref: '#/components/correlationIds/petsCorrelationId'
              headers:
                type: object
                properties:
                  CorrelId:
                    type: string
                    format: /pets;cid={correlationId}
              payload:
                $ref: '#/components/schemas/petPayload'
bindings:
  composite0:
    type: asyncapi
    kind: server
    options:
      specs:
        http_api:
          catalog:
            catalog0:
              subject: petstore
              version: latest
      tcp:
        host: localhost
        port:
          - 8080
    exit: asyncapi0
