image:
  tag: develop-SNAPSHOT

livenessProbePort: 9090
readinessProbePort: 9090

service:
  ports:
    - port: 9090
      name: https

configMaps:
  - name: proto
    localPath: examples/grpc.echo/proto/*
    mountPath: proto

secrets:
  - name: tls
    mountPath: tls
    localPath: examples/grpc.echo/tls/*

keystorePassword: generated

verify: |
  $ grpcurl -insecure -proto examples/grpc.echo/proto/echo.proto -d '{"message":"Hello World"}' localhost:9090 example.EchoService.EchoUnary
  {
    "message": "Hello World"
  }
  
  $ grpcurl -insecure -proto examples/grpc.echo/proto/echo.proto -d @ localhost:9090 example.EchoService.EchoBidiStream
  # type this:
  { "message": "Hello!" }
  # response:
  {
    "message": "Hello!"
  }
