apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/instance: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zookeeper
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: "bitnami/zookeeper:latest"
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
          readinessProbe:
            exec:
              command: ['/bin/bash', '-c', 'echo srvr | nc -w 2 localhost 2181']
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app.kubernetes.io/instance: zookeeper
  ports:
    - name: zookeeper
      port: 2181
  type: ClusterIP
