extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated
  - name: JAVA_OPTIONS
    value: "-Dzilla.incubator.enabled=true"

livenessProbePort: 7114
readinessProbePort: 7114

service:
  ports:
    - port: 7114
      name: http
    - port: 7143
      name: https
