version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:latest"
    command: "start"
    hostname: "zilla"
    volumes:
      - ./.zilla/zilla.properties:/.zilla/zilla.properties:ro
      - ./zilla.json:/zilla.json:ro
      - ./localhost.p12:/localhost.p12:ro
      - ./web:/web:ro
    networks:
      - net0
    ports:
      - "8080:8080"
      - "9090:9090"

  kafka:
    image: "bitnami/kafka:3"
    hostname: "kafka.internal.net"
    networks:
      - net0
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper.internal.net:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka.internal.net:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_PROTOCOL=PLAINTEXT
    ports:
      - "9092:9092"

  zookeeper:
    image: 'bitnami/zookeeper:3'
    hostname: "zookeeper.internal.net"
    networks:
      - net0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
