#!/bin/sh
version="develop-SNAPSHOT"
localPath="$HOME/.m2/repository/io/aklivity/zilla/manager/$version/manager-$version.jar"
wrappedPath=".zpm/wrapper/manager-$version.jar"
wrappedURL="https://maven.packages.aklivity.io/io/aklivity/zilla/manager/$version/manager-$version.jar"
if [ ! -r "$wrappedPath" ]; then
mkdir -p `dirname $wrappedPath`
if [ -r "$localPath" ]; then
echo $wrappedPath not found, copying from $localPath
cp $localPath $wrappedPath
else
echo $wrappedPath not found, downloading from $wrappedURL
if command -v wget > /dev/null; then
wget -O "$wrappedPath" "$wrappedURL" -nv
else
echo wget missing, download failed
fi
fi
fi
java $JAVA_OPTIONS -jar "$wrappedPath" "$@"
