{
    "name": "test",
    "guards":
    {
        "jwt0":
        {
            "type": "jwt",
            "options":
            {
                "issuer": "https://aklivity.us.auth0.com",
                "audience": "https://api.aklivity.com",
                "keys": "https://aklivity.us.auth0.com/.well-known/jwks.json",
                "challenge": 30
            }
        }
    }
}
