---
name: test
bindings:
  app0:
    type: kafka
    kind: cache_client
    options:
      merged:
        - test
    routes:
      - exit: cache0
        when:
          - topic: test
  cache0:
    type: kafka
    kind: cache_server
    routes:
      - exit: app1
        when:
          - topic: test
