#
# Copyright 2021-2026 Aklivity Inc.
#
# Aklivity licenses this file to you under the Apache License,
# version 2.0 (the "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at:
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#

---
name: test
telemetry:
  exporters:
    exporter0:
      type: test
      options:
        events:
          - qname: engine:events
            id: engine.started
            name: ENGINE_STARTED
            message: Engine Started.
          - qname: test:app0
            id: binding.kafka.broker.connection.failed
            name: BINDING_KAFKA_BROKER_CONNECTION_FAILED
            message: "Broker connection failed for host (localhost), port (9092)."
          - qname: engine:events
            id: engine.stopped
            name: ENGINE_STOPPED
            message: Engine Stopped.
bindings:
  app0:
    type: kafka
    kind: client
    options:
      servers:
        - localhost:9092
    routes:
      - exit: net0
