---
name: test
bindings:
    app0:
        type: kafka
        kind: client
        options:
            sasl:
                mechanism: scram-sha-1
                username: user
                password: pencil
        routes:
            - exit: net0
