---
name: test
bindings:
    app0:
        type: kafka
        kind: client
        options:
            sasl:
                mechanism: plain
                username: username
                password: password
        routes:
            - exit: net0
