image:
  tag: develop-SNAPSHOT

livenessProbePort: 1883
readinessProbePort: 1883

service:
  ports:
    - port: 1883
      name: mqtt
    - port: 8883
      name: mqtts

secrets:
  - name: tls
    mountPath: tls
    localPath: examples/mqtt.reflect/tls/*

keystorePassword: generated
