env:
  - name: KEYSTORE_PASSWORD
    value: generated
  - name: SASL_USERNAME
    value: user
  - name: SASL_PASSWORD
    value: redpanda

livenessProbePort: 7114
readinessProbePort: 7114

service:
  ports:
    - port: 7114
      name: http
    - port: 7143
      name: https
