extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated
  - name: KAFKA_HOST
    value: ""
  - name: KAFKA_PORT
    value: ""
  - name: ZILLA_INCUBATOR_ENABLED
    value: "true"

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7183
      name: mqtt
