name: ${NAMESPACE:-zilla-tcp-proxy}
services:
  iperf-server:
    image: networkstatic/iperf3
    container_name: iperf-server
    command: -s
    ports:
      - "5201:5201"

  zilla:
    image: ghcr.io/aklivity/zilla::${ZILLA_VERSION:-latest}
    restart: unless-stopped
    hostname: zilla.examples.dev
    ports:
      - "12345:12345"
    volumes:
      - ./etc:/etc/zilla
    command: start -v -e -Pzilla.engine.maximum.messages.per.read=10
    depends_on:
      - iperf-server

  iperf-client:
    image: networkstatic/iperf3
    container_name: iperf-client
    entrypoint: >
      sh -c "sleep 10 &&
           iperf3 -c zilla.examples.dev -p 12345 -P 50 -t 20"

networks:
  default:
    driver: bridge
