apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilla-config
  labels:
    app.kubernetes.io/instance: zilla-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zilla-config
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zilla-config
    spec:
      containers:
        - name: zilla-config
          image: "ghcr.io/aklivity/zilla:latest"
          args: ["start", "-v", "-e"]
          env:
            - name: KEYSTORE_PASSWORD
              value: generated
          ports:
            - containerPort: 8081
            - containerPort: 9091
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /etc/zilla
            - name: tls
              mountPath: /etc/zilla/tls
            - name: zilla-web
              mountPath: /var/www
      volumes:
        - name: config
          configMap:
            name: zilla
        - name: tls
          secret:
            secretName: tls
            items:
            - key: localhost.p12
              path: localhost.p12
        - name: zilla-web
          persistentVolumeClaim:
            claimName: zilla-web
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zilla
data:
  zilla.yaml: |-
{{ .Files.Get "files/zilla.yaml" | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tls
type: Opaque
data:
  localhost.p12: |-
{{ .Files.Get "files/localhost.p12" | b64enc | indent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zilla-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zilla-config
spec:
  selector:
    app.kubernetes.io/instance: zilla-config
  ports:
    - name: http
      port: 8081
    - name: https
      port: 9091
  type: ClusterIP
