#
# Copyright 2021-2026 Aklivity Inc
#
# Licensed under the Aklivity Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
#   https://www.aklivity.io/aklivity-community-license/
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#

---
name: test
guards:
  x509_0:
    type: x509
    options:
      identity: subject.cn
      attributes:
        organization: subject.o
        tenant: san.uri
      roles:
        partner:
          - issuer.cn: "Partner Issuing CA"
        internal:
          - issuer.cn: "Internal CA"
            subject.ou: "Platform"
          - issuer.cn: "Internal CA"
            san.dns: "*.internal.example.com"
bindings:
  net0:
    type: test
    kind: server
    options:
      authorization:
        x509_0:
          expectIdentity: platform.example.com
          attributes:
            organization: Example Inc
            tenant: spiffe://example.com/ns/prod/sa/platform
          credentials: |
            -----BEGIN CERTIFICATE-----
            MIIEMDCCAxigAwIBAgIUD8pFwjuLz3rkovbAuHTvDrgZLSswDQYJKoZIhvcNAQEL
            BQAwOTELMAkGA1UEBhMCVVMxFDASBgNVBAoMC0V4YW1wbGUgSW5jMRQwEgYDVQQD
            DAtJbnRlcm5hbCBDQTAgFw0yNjA4MDcyMzAxMTRaGA8yMTI2MDcxNDIzMDExNFow
            azELMAkGA1UEBhMCVVMxFDASBgNVBAoMC0V4YW1wbGUgSW5jMREwDwYDVQQLDAhQ
            bGF0Zm9ybTEUMBIGA1UECwwLRW5naW5lZXJpbmcxHTAbBgNVBAMMFHBsYXRmb3Jt
            LmV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2sDW
            5seIa8RyIvxeSVNZscRkB+p7WDd0l3Q+loHHcFl/VJkELyB08OAPpg+VOTybwN6Y
            8y1vcrO9uJD6V52auO1PDh4e2fYKSdFcFA8uNPg+MsCqjR3wlGH5I5ws6c02tiKf
            L4pn3m9vIWwhwKbqd+cxj/FqIXNsg/2DAclkO1eOV4Ng8p+mw3L6VDfNJjVYA8ix
            yCfrXq45VsCNq6Hmy9OLd6i1cvYmtoyTmFqZfiLkoXL+PuzB6aM1QvpEnxFU+4iu
            DL7XW9vCB1CATqd1ZoFUsNboROJI+8yfl0Nqff1vpK/HxLxnN8SGyk+Vx6XOkKkj
            cUyDvFu0UQz8JRfwvwIDAQABo4H7MIH4MAkGA1UdEwQCMAAwDgYDVR0PAQH/BAQD
            AgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMCMIGFBgNVHREEfjB8gh1wbGF0Zm9ybS5p
            bnRlcm5hbC5leGFtcGxlLmNvbYIbZXZlbnRzLmludGVybmFsLmV4YW1wbGUuY29t
            hihzcGlmZmU6Ly9leGFtcGxlLmNvbS9ucy9wcm9kL3NhL3BsYXRmb3JtgRRwbGF0
            Zm9ybUBleGFtcGxlLmNvbTAdBgNVHQ4EFgQUTdJ6ixVJAC7DfOo3gTQqiSZM828w
            HwYDVR0jBBgwFoAUT9HUpRhKserSwSIXg8elBd/RdGswDQYJKoZIhvcNAQELBQAD
            ggEBAFxumPHXwGPT5Kqu08J/Ky2QymgsDLdNtImh7uFVoPBM2tZVnLHnlu+xyXcE
            p/4XMwQACqA0A+SSh+kXaZS54XoqsB/Uz1ADsxoYQRDoD3LJuONBEDUcsdjiGNq0
            ekq4qhub3t4r61QBYtMNZwNneLqv5Z7O2IUXHnC13mnzRrMfmvGDcwTRaXo/qLCF
            pKZc2ALJ8dLXfsQsHnySV2/F3k5bBATcoxAmZmIOjauEfbEHwnlGfkFBoGztFwiV
            mjrEU9lximH3AMT0NmzkKT9CJOTLExtTSN5a1C2/yaBCROuJU26VSMMDK8s7wlfi
            CYYlj6BfhJjXtReHz0cPfdjmAYw=
            -----END CERTIFICATE-----
            -----BEGIN CERTIFICATE-----
            MIIDZTCCAk2gAwIBAgIURP6ynUy856EcfUN21iEMwTYf3/swDQYJKoZIhvcNAQEL
            BQAwOTELMAkGA1UEBhMCVVMxFDASBgNVBAoMC0V4YW1wbGUgSW5jMRQwEgYDVQQD
            DAtJbnRlcm5hbCBDQTAgFw0yNjA4MDcyMzAxMTRaGA8yMTI2MDcxNDIzMDExNFow
            OTELMAkGA1UEBhMCVVMxFDASBgNVBAoMC0V4YW1wbGUgSW5jMRQwEgYDVQQDDAtJ
            bnRlcm5hbCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALmzNZ4s
            17lBim6L/jGslFykk/feaL7fRaQITNirftuO5VBzRysSpzlcF60vmbL1f324yUpW
            iRqX9aZVaBuvi08Eua5ooizUmqL31znxfXNitKsxsiNISBDWSMcTfidkrLt65rFk
            DTIqDYTIICoYV9SQNI3iWtUmBHsC7J2uf1ztokcvbDcoV4adEiA3E9Nx5G8klVp6
            D+sGVIWvvneWrrsI/I9Vr7pipsLL5C4XI30usfaUcSBO2f4sDtvzSNesM2ziomMN
            u0c+Tbb+OrIZJ40zSflXDYlLkuckUMQpYPk7uSa/250XwstaLTXvn3Kdw8mxEZn7
            Vk4wo3G+J8HQvc0CAwEAAaNjMGEwHQYDVR0OBBYEFE/R1KUYSrHq0sEiF4PHpQXf
            0XRrMB8GA1UdIwQYMBaAFE/R1KUYSrHq0sEiF4PHpQXf0XRrMA8GA1UdEwEB/wQF
            MAMBAf8wDgYDVR0PAQH/BAQDAgEGMA0GCSqGSIb3DQEBCwUAA4IBAQCGj3onF6Ax
            j2zJ6+Qvwe1eFcec5NH+2O9FxeI9Q/+4kEYn0TfxN6Efq9BHtzBNsTiZU7b5hOIO
            I1EAXbsa6TCkJFs4yZs2LxEaNRMBdHmUMYs5wO0M+1VeGal+VpEurdA+aAHqnrmd
            dRXgIYBZ9Baq3N9OjsdvVCgo8o0s/kOzCDaRr/iMZSYPCv3hQ+9nZIuH11b8K5X0
            q/GIAKX5giLsMyM41LRNvtLfpaQjkcdK37dIVkvSGbD9XAk+vJ/KUoCj6j1brLQb
            8We2w4cQU5L46YhyGN15KbiLKC1j1xQoxqG1lV/4+vrZfntI/dL+c1e/MnqgQHoW
            B6tpqa25/p3q
            -----END CERTIFICATE-----
    routes:
      - guarded:
          x509_0:
            - internal
        exit: app0
