replicaCount: 1

args: ["start", "-v", "-e", "-Pzilla.engine.worker.capacity=512"]

env:
  KAFKA_BOOTSTRAP_SERVER: "kafka.svc.cluster.local:9092"
  ROUTE_GUIDE_SERVER_HOST: "route-guide-server.svc.cluster.local"
  ROUTE_GUIDE_SERVER_PORT: "50051"
  ZILLA_INCUBATOR_ENABLED: "true"

livenessProbePort: 7190
readinessProbePort: 7190

service:
  ports:
    - port: 7114
      name: http
    - port: 7183
      name: mqtt
    - port: 7151
      name: grpc
    - port: 7190
      name: metrics
