extraEnv:
  - name: KEYSTORE_PASSWORD
    value: generated
  - name: JAVA_OPTIONS
    value: "-Dzilla.incubator.enabled=true"

livenessProbePort: 7143
readinessProbePort: 7143

service:
  ports:
    - port: 7143
      name: https
