version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:latest"
    hostname: "zilla"
    command: [ "start", "-v", "-e" ]
    volumes:
      - ./zilla.yaml:/etc/zilla/zilla.yaml:ro
    networks:
      - net0
    ports:
      - "12345:12345"
