apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app.kubernetes.io/instance: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kafka
    spec:
      containers:
        - name: kafka
          image: "bitnami/kafka:3.2"
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LOG_DIRS
              value: "/tmp/logs"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_LISTENERS
              value: "INTERNAL://:9092,CLIENT://:29092,CONTROLLER://:9093"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka.zilla-kafka-broker.svc.cluster.local:9092,CLIENT://localhost:29092"
          ports:
            - containerPort: 9092
            - containerPort: 29092
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app.kubernetes.io/instance: kafka
  ports:
    - name: broker-kafka
      port: 9092
    - name: broker-localhost
      port: 29092
  type: ClusterIP
