apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app.kubernetes.io/instance: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kafka
    spec:
      containers:
        - name: kafka
          args:
            - /bin/sh
            - -c
            - /opt/bitnami/scripts/kafka/setup.sh && kafka-storage.sh format --config "${KAFKA_CONF_FILE}" --cluster-id "lkorDA4qT6W1K_dk0LHvtg" --ignore-formatted && /opt/bitnami/scripts/kafka/run.sh
          image: "bitnami/kafka:3.1.0"
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@127.0.0.1:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_LOG_DIRS
              value: "/tmp/logs"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_LISTENERS
              value: "CLIENT://:9092,INTERNAL://:29092,CONTROLLER://:9093"
            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "CLIENT://localhost:9092,INTERNAL://kafka:29092"
          ports:
            - containerPort: 9092
            - containerPort: 29092
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app.kubernetes.io/instance: kafka
  ports:
    - name: broker-localhost
      port: 9092
    - name: broker-kafka
      port: 29092
  type: ClusterIP
