apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-echo
  labels:
    app.kubernetes.io/instance: grpc-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: grpc-echo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grpc-echo
    spec:
      containers:
        - name: grpc-echo
          image: "ghcr.io/aklivity/extras-grpc-echo-server:sha-478b2ce"
          args: ["--port", "50051"]
          ports:
            - containerPort: 50051
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 3
            periodSeconds: 5
          tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-echo
spec:
  selector:
    app.kubernetes.io/instance: grpc-echo
  ports:
    - name: http
      port: 50051
  type: ClusterIP
