service:
  port: 8080
yamlApplicationConfig:
  kafka:
    clusters:
      - name: local
        bootstrapServers: kafka.zilla-kafka-broker.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
