---
name: example
telemetry:
  metrics:
    - http.request.size
    - http.response.size
    - stream.active.received
    - stream.active.sent
    - stream.opens.received
    - stream.opens.sent
    - stream.data.received
    - stream.data.sent
    - stream.errors.received
    - stream.errors.sent
    - stream.closes.received
    - stream.closes.sent
  exporters:
    prometheus_endpoint:
      type: prometheus
      options:
        endpoints:
          - scheme: http
            path: /metrics
            port: 9090
bindings:
  north_tcp_server:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port: 8080
    telemetry:
      metrics:
        - stream.*
    exit: north_http_server
  north_http_server:
    type: http
    kind: server
    routes:
      - when:
          - headers:
              :scheme: http
              :authority: localhost:8080
        exit: north_echo_server
    telemetry:
      metrics:
        - http.*
  north_echo_server:
    type: echo
    kind: server
