version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:0.9.10"
    command: "start"
    hostname: "zilla"
    volumes:
      - ./.zilla/zilla.properties:/.zilla/zilla.properties:ro
      - ./zilla.json:/zilla.json:ro
      - ./localhost.p12:/localhost.p12:ro
    networks:
      - net0
    ports:
      - "23456:23456"
