version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:latest"
    hostname: "zilla"
    command: [ "start", "-v", "-e" ]
    volumes:
      - ./zilla.json:/zilla.json:ro
      - ./localhost.p12:/localhost.p12:ro
    networks:
      - net0
    ports:
      - "23456:23456"
