scrape_configs:
  - job_name: zilla
    scrape_interval: 10s
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - zilla-kubernetes-prometheus-autoscale
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_name
        target_label: pod
      - source_labels:
          - __meta_kubernetes_service_name
        target_label: service
      - source_labels:
          - namespace
        target_label: exported_namespace
      - source_labels:
          - __meta_kubernetes_namespace
        target_label: namespace
      - target_label: endpoint
        replacement: prometheus
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+):.*
        replacement: $1:7190 # port you want to use
        target_label: __address__
