/*
 * Copyright 2021-2026 Aklivity Inc.
 *
 * Aklivity licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.aklivity.zilla.runtime.engine.store;

import java.io.Closeable;
import java.time.Duration;
import java.util.function.BiConsumer;
import java.util.function.Consumer;

/**
 * Provides key-value state operations for streams passing through a binding backed by a store.
 * <p>
 * A {@code StoreHandler} is obtained from {@link StoreContext#attach(StoreConfig)} and is
 * confined to a single I/O thread. It maintains mutable runtime state — session tokens, JWKS
 * keys, idempotency records, rate-limit counters, OAuth nonces — and evaluates operations on
 * the hot path without blocking or holding the calling thread.
 * </p>
 * <p>
 * <b>All operations complete asynchronously.</b> Each method takes a completion callback. The
 * callback fires <em>strictly later</em> than the call returns — never synchronously, even
 * when the underlying backend can compute the result inline. The callback fires on the
 * caller's I/O thread; the implementation owns the responsibility for thread alignment. For a
 * local backend this means deferring via the engine signaler to the next event-loop tick of
 * the same worker; for a networked backend it means hopping the network-completion event
 * back onto the calling worker's signaler before invoking the callback. In either case the
 * caller observes "callback runs on my thread, later".
 * </p>
 * <p>
 * The result of an operation is only valid inside the callback.
 * </p>
 *
 * @see StoreContext
 */
public interface StoreHandler
{
    /**
     * Retrieves the value associated with the given key.
     *
     * @param key        the key to look up
     * @param completion a callback that receives {@code (key, value)};
     *                   {@code value} is {@code null} if the key is not present
     */
    void get(
        String key,
        BiConsumer<String, String> completion);

    /**
     * Associates the given value with the given key, replacing any existing value.
     *
     * @param key        the key to store
     * @param value      the value to associate
     * @param ttl        the time-to-live, or {@code null} for no expiry
     * @param completion a callback invoked when the operation completes
     */
    void put(
        String key,
        String value,
        Duration ttl,
        Consumer<String> completion);

    /**
     * Associates the given value with the given key only if the key is not already present.
     *
     * @param key        the key to store
     * @param value      the value to associate if absent
     * @param ttl        the time-to-live, or {@code null} for no expiry
     * @param completion a callback that receives the existing value if present,
     *                   or {@code null} if the key was absent and the value was stored
     */
    void putIfAbsent(
        String key,
        String value,
        Duration ttl,
        Consumer<String> completion);

    /**
     * Removes the entry for the given key.
     *
     * @param key        the key to remove
     * @param completion a callback invoked when the operation completes
     */
    void delete(
        String key,
        Consumer<String> completion);

    /**
     * Atomically retrieves and removes the entry for the given key.
     *
     * @param key        the key to retrieve and remove
     * @param completion a callback that receives the value that was removed,
     *                   or {@code null} if the key was not present
     */
    void getAndDelete(
        String key,
        Consumer<String> completion);

    /**
     * Attempts to acquire a TTL-bounded lock on the given key without waiting.
     * <p>
     * The completion fires <em>strictly later</em> than the call returns, on the caller's I/O
     * thread, following the same async contract as the other {@code StoreHandler} operations.
     * On success it receives a non-null ownership token, generated by the implementation, that
     * the caller must supply to {@link #unlock} to release. On contention — another holder owns
     * an unexpired lock — the completion receives {@code null}.
     * </p>
     * <p>
     * The lock auto-releases when its TTL elapses; an {@code unlock} from the original holder
     * against an expired or reacquired lock is treated as a no-op.
     * </p>
     *
     * @param key         the key to lock
     * @param ttl         the lease duration, or {@code null} for no expiry
     * @param completion  a callback that receives {@code (key, token)};
     *                    {@code token} is non-null when the lock was acquired,
     *                    {@code null} when another holder owns the key
     */
    void lock(
        String key,
        Duration ttl,
        BiConsumer<String, String> completion);

    /**
     * Releases a lock previously acquired via {@link #lock}, provided the supplied token matches
     * the current holder.
     * <p>
     * On a successful ownership-checked release, the completion receives the supplied token —
     * mirroring the {@link #lock} completion shape (non-null = you own it). On failure — the
     * supplied token does not match the current holder, or the lock has already expired or been
     * released — the completion receives {@code null}. No information about another holder is
     * surfaced to a caller that did not prove ownership.
     * </p>
     * <p>
     * The completion fires <em>strictly later</em> than the call returns, on the caller's I/O
     * thread, following the same async contract as the other {@code StoreHandler} operations.
     * </p>
     *
     * @param key         the key to unlock
     * @param token       the ownership token returned by a prior {@link #lock} call
     * @param completion  a callback that receives the supplied {@code token} on a successful
     *                    ownership-checked release, or {@code null} otherwise
     */
    void unlock(
        String key,
        String token,
        Consumer<String> completion);

    /**
     * Extends the TTL of a lock previously acquired via {@link #lock}, provided the supplied token
     * matches the current holder.
     * <p>
     * Used by callers that hold a lock longer than its initial TTL — for example, a singleton
     * worker that owns a coordination lease for the lifetime of its binding. The caller schedules
     * renewals at an interval shorter than the lease TTL; if any renewal fails the caller has
     * lost ownership and must surrender any externally-visible state predicated on holding the
     * lock.
     * </p>
     * <p>
     * On a successful ownership-checked renewal, the completion receives the supplied token and
     * the lock's expiry is reset to {@code now + ttl}. On failure — the token does not match the
     * current holder, or the lock has already expired and possibly been reacquired by another
     * holder — the completion receives {@code null}. As with {@link #unlock}, the implementation
     * does not surface information about another holder to a caller that did not prove ownership.
     * </p>
     * <p>
     * The completion fires <em>strictly later</em> than the call returns, on the caller's I/O
     * thread, following the same async contract as the other {@code StoreHandler} operations.
     * </p>
     *
     * @param key         the key whose lock is being renewed
     * @param token       the ownership token returned by a prior {@link #lock} call
     * @param ttl         the new lease duration counted from now, or {@code null} for no expiry
     * @param completion  a callback that receives the supplied {@code token} on a successful
     *                    ownership-checked renewal, or {@code null} otherwise
     */
    void renew(
        String key,
        String token,
        Duration ttl,
        Consumer<String> completion);

    /**
     * Registers a listener invoked when the value associated with the given key changes.
     * <p>
     * Registration returns synchronously. The listener fires <em>strictly later</em> than the
     * mutation that triggered it, on the registering caller's I/O thread, following the same
     * async contract as the other {@code StoreHandler} operations. Each invocation receives the
     * key and the new value, or {@code null} when the entry has been removed.
     * </p>
     * <p>
     * Implementations decide the scope of change visibility — in-process, node-wide, or
     * cluster-wide — and document it in their module.
     * </p>
     *
     * @param key       the key to observe
     * @param listener  a callback that receives {@code (key, value)} on every change;
     *                  {@code value} is {@code null} when the entry has been removed
     * @return a {@link Closeable} handle that unsubscribes the listener when closed
     */
    Closeable watch(
        String key,
        BiConsumer<String, String> listener);
}
