---
name: test
bindings:
    net0:
        type: http
        kind: server
        options:
            versions:
                - http/1.1
            access-control:
                policy: cross-origin
                allow:
                    origins:
                        - https://example.net:9090
                    methods:
                        - GET
                        - DELETE
                    headers:
                        - x-api-key
                max-age: 10
        routes:
            - exit: app0
              when:
                  - headers:
                        :scheme: https
                        :authority: example.com:9090
