---
name: test
guards:
    test0:
        type: test
        options:
            credentials: TOKEN
            lifetime: PT5S
            challenge: PT5S
bindings:
    net0:
        type: http
        kind: server
        options:
            versions:
                - http/1.1
            authorization:
                test0:
                    credentials:
                        cookies:
                            access_token: "{credentials}"
                        headers:
                            authorization: Bearer {credentials}
                        query:
                            access_token: "{credentials}"
        routes:
            - exit: app0
              guarded:
                  test0: []
