#
# Copyright 2021-2026 Aklivity Inc
#
# Licensed under the Aklivity Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
#   https://www.aklivity.io/aklivity-community-license/
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#

---
name: test
telemetry:
    metrics:
        - mcp.tools.call
        - mcp.tools.call.duration
        - mcp.tools.list
        - mcp.prompts.get
        - mcp.resources.read
    exporters:
        exporter0:
            type: test
            options:
                metrics:
                    - name: mcp.prompts.get
                      binding: app0
                      kind: counter
                      value: 1
                    - name: mcp.tools.call
                      binding: app0
                      kind: counter
                      value: 0
bindings:
    app0:
        type: test
        kind: proxy
        options:
            originType: mcp
        routes:
            - exit: app1
        telemetry:
            metrics:
                - mcp.*
