/*
 * Copyright 2021-2023 Aklivity Inc
 *
 * Licensed under the Aklivity Community License (the "License"); you may not use
 * this file except in compliance with the License.  You may obtain a copy of the
 * License at
 *
 *   https://www.aklivity.io/aklivity-community-license/
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OF ANY KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations under the License.
 */
scope internal
{
    scope queue
    {
        struct GrpcQueueMessage
        {
            int32 correlationIdLength;
            octets[correlationIdLength] correlationId = null;
            int32 serviceLength;
            octets[serviceLength] service = null;
            int32 methodLength;
            octets[methodLength] method = null;
            int64 traceId;
            int64 authorization;
            int32 partitionId;
            int64 partitionOffset;
            int32 deferred;
            uint8 flags = 3;                    // 0x01 FIN, 0x02 INIT, 0x04 INCOMPLETE, 0x08 SKIP
            int32 reserved;
            int32 valueLength;
            octets[valueLength] value = null;
        }
    }
}
