livenessProbePort: 8080
readinessProbePort: 8080

service:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: https

tls:
  enabled: true
  keystore:
    name: localhost.p12
    localPath: examples/http.echo/localhost.p12
    mountPath: /etc/zilla/tls
    password: generated

verify: |
  $ curl -d "Hello, world" -H "Content-Type: text/plain" -X "POST" http://localhost:8080/
  Hello, world

  $ curl -d "Hello, world" -H "Content-Type: text/plain" -X "POST" http://localhost:8080/ --http2-prior-knowledge
  Hello, world

  $ curl --cacert examples/http.echo/test-ca.crt -d "Hello, world" -H "Content-Type: text/plain" -X "POST" https://localhost:9090/ --http1.1
  Hello, world

  $ curl --cacert examples/http.echo/test-ca.crt -d "Hello, world" -H "Content-Type: text/plain" -X "POST" https://localhost:9090/ --http2
  Hello, world
