livenessProbePort: 8080
readinessProbePort: 8080

service:
  port: 8080

tls:
  enabled: true
  keystorePath: localhost.p12
  keystoreLocalPath: examples/http.echo/localhost.p12
  keystorePassword: generated
