---
name: test
bindings:
  app0:
    type: ws
    kind: client
    options:
      defaults:
        protocol: primary
        scheme: http
        authority: localhost:8080
        path: /echo
    routes:
      - exit: net0
        when:
          - protocol: primary
