{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls
type: Opaque
data:
  {{ .Values.tls.keystore.name }}: {{ .Files.Get .Values.tls.keystore.localPath | b64enc }}
{{- end }}
