{{ range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
type: Opaque
data:
{{- range $key, $value := $secret.data }}
{{ $key | indent 2 }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
