{{- if eq (include "helm.isServicePortDefined" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - port: {{ $port.port }}
      protocol: TCP
      name: {{ $port.name }}
  {{- end }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
{{- end }}
