/*
 * Copyright 2021-2026 Aklivity Inc.
 *
 * Aklivity licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
scope protocol
{
    option byteorder network;

    scope codec
    {
        struct RequestHeader
        {
            int32 length;
            int16 apiKey;
            int16 apiVersion;
            int32 correlationId;
            string16 clientId /* = null */;
        }

        struct ResponseHeader
        {
            int32 length;
        }

        struct ResponseErrorCode
        {
            int16 errorCode;
        }

        scope message
        {
            struct RecordSet
            {
                int32 length;
            }

            struct RecordBatch
            {
                int64 baseOffset;
                int32 length;
                int32 leaderEpoch;
                int8  magic;
                int32 crc;
                int16 attributes;
                int32 lastOffsetDelta;
                int64 firstTimestamp;
                int64 maxTimestamp;
                int64 producerId;
                int16 producerEpoch;
                int32 baseSequence;
                int32 recordCount;
            }

            struct RecordHeader
            {
                varint32 length;
                int8   attributes;
                varint32 timestampDelta;
                varint32 offsetDelta;
                varint32 keyLength;
                octets[keyLength] key = null;
                varint32 valueLength;
            }

            struct RecordTrailer
            {
                varint32 headerCount;
            }

            struct MessageHeader
            {
                varint32 keyLength;
                octets[keyLength] key; // UTF-8 bytes
                varint32 valueLength;
                octets[valueLength] value = null;
            }
        }

        scope config
        {
            struct DescribeConfigsRequest
            {
              int32 resourceCount;
            }

            struct ResourceRequest
            {
                int8 type;
                string16 name;
                int32 configNamesCount;
            }

            struct DescribeConfigsRequestCompleted
            {
                uint8 includeSynonyms;
            }

            struct DescribeConfigsResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int32 resourceCount;
            }

            struct ResourceResponse
            {
                int16 errorCode;
                string16 errorMessage;
                int8 type;
                string16 name;
                int32 configCount;
            }

            struct ConfigResponse
            {
                string16 name;
                string16 value;
                int8 isReadOnly;
                int8 configSource;
                int8 isSensitive;
                int32 synonyms;
            }

            struct SynonymResponse
            {
                string16 name;
                string16 value;
                int8 source;
            }
        }

        scope fetch
        {
            struct FetchRequest
            {
                int32 replicaId = -1;
                int32 maxWaitTimeMillis;
                int32 minBytes;
                int32 maxBytes;
                int8 isolationLevel;
                int32 topicCount;
            }

            struct TopicRequest
            {
                string16 name;
                int32 partitionCount;
            }

            struct PartitionRequest
            {
                int32 partitionId;
                int64 fetchOffset;
                int64 logStartOffset = -1;
                int32 maxBytes;
            }

            struct FetchResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int32 topicCount;
            }

            struct TopicResponse
            {
                string16 name;
                int32 partitionCount;
            }

            struct PartitionResponse
            {
                int32 partitionId;
                int16 errorCode;
                int64 highWatermark;
                int64 lastStableOffset;
                int64 logStartOffset;
                int32 abortedTransactionCount;
            }

            struct TransactionResponse
            {
                int64 producerId;
                int64 firstOffset;
            }

            enum ControlRecordKeyType
            {
                ABORT,
                COMMIT
            }

            struct ControlRecordKey
            {
                int16 version;
                int16 type;
            }
        }

        scope offsets
        {
            enum IsolationLevel
            {
                READ_UNCOMMITTED,
                READ_COMMITTED
            }

            struct OffsetsRequest // version 2
            {
                int32 replicaId = -1;
                IsolationLevel isolationLevel;
                int32 topicCount;
            }

            struct OffsetsTopicRequest
            {
                string16 name;
                int32 partitionCount;
            }

            struct OffsetsPartitionRequest
            {
                int32 partitionId;
                int64 timestamp = -2;
            }

            struct OffsetsResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int32 topicCount;
            }

            struct OffsetsTopicResponse
            {
                string16 name;
                int32 partitionCount;
            }

            struct OffsetsPartitionResponse
            {
                int32 partitionId;
                int16 errorCode;
                int64 timestamp;
                int64 offset;
            }
        }

        scope metadata
        {
            struct MetadataRequest
            {
                int32 topicCount = 1;
                string16 topicName;   // TODO: string array
                int8 allow_auto_topic_creation = 0;
            }

            struct MetadataResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int32 brokerCount;
            }

            struct BrokerMetadata
            {
                int32 nodeId;
                string16 host;
                int32 port;
                string16 rack; // = null
            }

            struct MetadataResponsePart2
            {
                string16 clusterId;
                int32 controllerId;
                int32 topicCount;
            }

            struct TopicMetadata
            {
                int16 errorCode;
                string16 topic;
                int8 isInternal;
                int32 partitionCount;
            }

            struct PartitionMetadata
            {
                int16 errorCode;
                int32 partitionId;
                int32 leader;
                int32 replicaCount;
                int32[replicaCount] replicas = null;
                int32 inSyncReplicasCount;
                int32[inSyncReplicasCount] inSyncReplicas = null;
                int32 offlineReplicasCount;
                int32[offlineReplicasCount] offlineReplicas = null;
            }
        }

        scope produce
        {
            struct ProduceRequest // v3
            {
                string16 transactionalId;
                int16 acks;
                int32 timeout;
                int32 topicCount;
            }

            struct ProduceTopicRequest
            {
                string16 topic;
                int32 partitionCount;
            }

            struct ProducePartitionRequest
            {
                int32 partitionId;
                int32 recordSetLength;
            }

            struct ProduceResponse // v3
            {
                int32 correlationId;
                int32 topicCount;
            }

            struct ProduceTopicResponse
            {
                string16 topic;
                int32 partitionCount;
            }

            struct ProducePartitionResponse
            {
                int32 partitionId;
                int16 errorCode;
                int64 baseOffset;
                int64 logAppendTime;
            }

            struct ProduceResponseTrailer
            {
                int32 throttleTimeMillis;
            }

            struct InitProducerIdRequest
            {
                string16 transaction = null;
                int32 transactionTimeoutMs = 60000;
                int64 producerId;
                int16 producerEpoch;
            }

            struct InitProducerIdResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int16 errorCode;
                int64 producerId;
                int16 producerEpoch;
            }
        }

        scope group
        {
            struct FindCoordinatorRequest
            {
                string16 key;
                int8 keyType;
            }

            struct FindCoordinatorResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int16 errorCode;
                string16 errorMessage = null;
                int32 nodeId;
                string16 host;
                int32 port;
            }

            struct JoinGroupRequest
            {
                string16 groupId;
                int32 sessionTimeoutMillis;
                int32 rebalanceTimeoutMillis;
                string16 memberId;
                string16 groupInstanceId = null;
                string16 protocolType;
                int32 protocolCount;
            }

            struct ProtocolMetadata
            {
                string16 name;
                uint32 metadataLength;
                octets[metadataLength] metadata;
            }

            struct RangeProtocol
            {
                int32 version;
                string16 topic;
                int32 partitionCount;
            }

            struct JoinGroupResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int16 errorCode;
                int32 generatedId;
                string16 protocolName;
                string16 leader;
                string16 memberId;
                int32 memberCount;
            }

            struct MemberMetadata
            {
                string16 memberId;
                string16 groupInstanceId = null;
                uint32 length;
                octets[length] metadata;
            }

            struct SyncGroupRequest
            {
                string16 groupId;
                int32 generatedId;
                string16 memberId;
                string16 groupInstanceId = null;
                int32 assignmentCount;
            }

            struct Assignment
            {
               string16 memberId;
               int32 length;
               octets[length] value = null;
            }

            struct Partition
            {
                int32 partitionId;
                int32 offsetId;
            }

            struct SyncGroupResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int16 errorCode;
                uint32 assignmentLength;
                octets[assignmentLength] assignment;
            }

            struct HeartbeatRequest
            {
                string16 groupId;
                int32 generatedId;
                string16 memberId;
                string16 groupInstanceId = null;
            }

            struct HeartbeatResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int16 errorCode;
            }

            struct LeaveGroupRequest
            {
                string16 groupId;
                int32 memberCount;
            }

            struct LeaveGroupResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int16 errorCode;
                int32 memberCount;
            }

            struct LeaveMemberRequest
            {
                string16 memberId;
                string16 groupInstanceId = null;
            }

            struct LeaveMemberResponse
            {
                string16 memberId;
                string16 groupInstanceId = null;
                int16 errorCode;
            }

            struct OffsetCommitRequest
            {
                string16 groupId;
                int32 generationId;
                string16 memberId;
                string16 groupInstanceId = null;
                int32 topicCount;
            }

            struct OffsetCommitTopicRequest
            {
                string16 name;
                int32 partitionCount;
            }

            struct OffsetCommitTopicPartitionRequest
            {
                int32 partitionIndex;
                int64 partitionOffset;
                int32 leaderEpoch;
                string16 metadata = null;
            }

            struct OffsetCommitResponse
            {
                int32 correlationId;
                int32 throttleTimeMs;
                int32 topicCount;
            }

            struct OffsetCommitTopicResponse
            {
                string16 name;
                int32 partitionCount;
            }

            struct OffsetCommitTopicPartitionResponse
            {
                int32 partitionIndex;
                int16 errorCode;
            }

            struct OffsetFetchRequest
            {
                string16 groupId;
                int32 topicCount;
            }

            struct OffsetFetchTopicRequest
            {
                string16 name;
                int32 partitionsCount;
            }

            struct OffsetFetchTopicPartitionRequest
            {
                int32 partitionIndex;
            }

            struct OffsetFetchResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int32 topicCount;
            }

            struct OffsetFetchTopicResponse
            {
                string16 name;
                int32 partitionCount;
            }

            struct OffsetFetchPartitionResponse
            {
                int32 partitionIndex;
                int64 committedOffset;
                int32 committedLeaderEpoch;
                string16 metadata = null;
                int16 errorCode;
            }

            struct OffsetFetchErrorResponse
            {
                int16 code;
            }
        }

        scope describe_cluster
        {
            struct DescribeClusterRequest // v0
            {
                varuint32 taggedFields;
            }

            struct DescribeClusterRequestPart2
            {
                uint8 includeAuthorizedOperations;
                varuint32 taggedFields;
            }

            struct DescribeClusterResponse
            {
                int32 correlationId;
                varuint32 taggedFields;
                int32 throttle;
                int16 error;
                varstring message;
                varstring clusterId;
                int32 controllerId;
                varuint32n brokerCount;
            }

            struct ClusterBroker
            {
                int32 brokerId;
                varstring host;
                int32 port;
                varstring rack;
                varuint32 taggedFields;
            }

            struct DescribeClusterResponsePart2
            {
                int32 clusterAuthorizedOperations;
                varuint32 taggedFields;
            }
        }

        scope create_topics
        {
            struct CreateTopicsRequest // v7
            {
                varuint32 taggedFields;
                varuint32n topicCount;
            }

            struct TopicRequest
            {
                varstring name;
                int32 partitions;
                int16 replicas;
                varuint32n assignmentCount;
            }

            struct AssignmentRequest
            {
               int32 partitionIndex;
               varuint32n brokerCount;
            }

            struct BrokerRequest
            {
                int32 brokerId;
            }

            struct AssignmentRequestPart2
            {
                varuint32 taggedFields;
            }

            struct ConfigsRequest
            {
                varuint32n configCount;
            }

            struct ConfigRequest
            {
                varstring name;
                varstring value = null;
                varuint32 taggedFields;
            }

            struct TopicRequestPart2
            {
                varuint32 taggedFields;
            }

            struct CreateTopicsRequestPart2
            {
                int32 timeout;
                uint8 validate_only;
                varuint32 taggedFields;
            }

            struct CreateTopicsResponse
            {
                int32 correlationId;
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n topicCount;
            }

            struct TopicResponse
            {
                varstring name;
                octets[16] topicId;
                int16 error;
                varstring message = null;
                int32 numPartitions;
                int16 replicationFactor;
                varuint32n configCount;
            }

            struct ConfigResponse
            {
                varstring name;
                varstring value = null;
                uint8 readOnly;
                int8 configSource;
                uint8 isSensitive;
                varuint32 taggedFields;
            }

            struct TopicResponsePart2
            {
                varuint32 taggedFields;
            }

            struct CreateTopicsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        scope delete_topics
        {
            struct DeleteTopicsRequest // v6
            {
                varuint32 taggedFields;
                varuint32n topicCount;
            }

            struct TopicRequest
            {
                varstring name;
                octets[16] topicId;
                varuint32 taggedFields;
            }

            struct DeleteTopicsRequestPart2
            {
                int32 timeout;
                varuint32 taggedFields;
            }

            struct DeleteTopicsResponse
            {
                int32 correlationId;
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n topicCount;
            }

            struct TopicResponse
            {
                varstring name = null;
                octets[16] topicId;
                int16 error;
                varstring message = null;
                varuint32 taggedFields;
            }

            struct DeleteTopicsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        scope topic_metadata
        {
            struct MetadataRequest // v9
            {
                varuint32 taggedFields;
                varuint32n topicCount;
            }

            struct TopicNameRequest
            {
                varstring name;
                varuint32 taggedFields;
            }

            struct MetadataRequestPart2
            {
                uint8 allowAutoTopicCreation;
                uint8 includeClusterAuthorizedOperations;
                uint8 includeTopicAuthorizedOperations;
                varuint32 taggedFields;
            }

            struct MetadataResponse
            {
                int32 correlationId;
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n brokerCount;
            }

            struct BrokerMetadata
            {
                int32 nodeId;
                varstring host;
                int32 port;
                varstring rack = null;
                varuint32 taggedFields;
            }

            struct MetadataResponsePart2
            {
                varstring clusterId = null;
                int32 controllerId;
                varuint32n topicCount;
            }

            struct TopicMetadata
            {
                int16 errorCode;
                varstring topic;
                uint8 isInternal;
                varuint32n partitionCount;
            }

            struct PartitionMetadata
            {
                int16 errorCode;
                int32 partitionId;
                int32 leader;
                int32 leaderEpoch;
                varuint32n replicaCount;
                int32[replicaCount] replicas = null;
                varuint32n isrCount;
                int32[isrCount] isr = null;
                varuint32n offlineReplicaCount;
                int32[offlineReplicaCount] offlineReplicas = null;
                varuint32 taggedFields;
            }

            struct TopicMetadataPart2
            {
                int32 topicAuthorizedOperations;
                varuint32 taggedFields;
            }

            struct MetadataResponsePart3
            {
                int32 clusterAuthorizedOperations;
                varuint32 taggedFields;
            }
        }

        scope find_coordinator
        {
            struct FindCoordinatorRequest // v3
            {
                varuint32 taggedFields;
                varstring key;
                int8 keyType;
            }

            struct FindCoordinatorRequestPart2
            {
                varuint32 taggedFields;
            }

            struct FindCoordinatorResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                int16 error;
                varstring message = null;
                int32 nodeId;
                varstring host;
                int32 port;
                varuint32 trailingTaggedFields;
            }
        }

        scope list_groups
        {
            struct ListGroupsRequest // v4
            {
                varuint32 taggedFields;
                varuint32n statesFilterCount;
            }

            struct ListGroupsRequestPart2
            {
                varuint32 taggedFields;
            }

            struct GroupResponse
            {
                varstring groupId;
                varstring protocolType;
                varstring groupState;
                varuint32 taggedFields;
            }

            struct ListGroupsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        scope describe_groups
        {
            struct DescribeGroupsRequest // v5
            {
                varuint32 taggedFields;
                varuint32n groupCount;
            }

            struct GroupIdRequest
            {
                varstring groupId;
            }

            struct DescribeGroupsRequestPart2
            {
                uint8 includeAuthorizedOperations;
                varuint32 taggedFields;
            }

            struct DescribedGroupResponse
            {
                int16 error;
                varstring groupId;
                varstring groupState;
                varstring protocolType;
                varstring protocolData;
                varuint32n memberCount;
            }

            struct DescribedGroupMemberResponse
            {
                varstring memberId;
                varstring groupInstanceId = null;
                varstring clientId;
                varstring clientHost;
            }

            struct DescribedGroupResponsePart2
            {
                int32 authorizedOperations;
                varuint32 taggedFields;
            }

            struct DescribeGroupsResponsePart2
            {
                varuint32 taggedFields;
            }
        }


        scope alter_configs
        {
            struct AlterConfigsRequest // v1
            {
                int32 resourceCount;
            }

            struct ResourceRequest
            {
                uint8 type;
                string16 name;
                int32 configCount;
            }

            struct ConfigRequest
            {
                string16 name;
                string16 value = null;
            }

            struct AlterConfigsRequestPart2
            {
                uint8 validate_only;
            }

            struct AlterConfigsResponse
            {
                int32 correlationId;
                int32 throttleTimeMillis;
                int32 resourceCount;
            }

            struct ResourceResponse
            {
                int16 error;
                string16 message = null;
                uint8 type;
                string16 name;
            }
        }

        // Flexible (compact strings/arrays + tagged fields) counterpart of scope alter_configs,
        // used only by the generic api envelope (KafkaApiRequestBeginEx/KafkaApiResponseBeginEx)
        // path, mirroring create_topics/delete_topics' use of the first flexible version of their
        // respective APIs rather than the older non-flexible version scope alter_configs targets.
        scope alter_configs_v2
        {
            struct AlterConfigsRequest // v2
            {
                varuint32 taggedFields;
                varuint32n resourceCount;
            }

            struct ResourceRequest
            {
                uint8 type;
                varstring name;
                varuint32n configCount;
            }

            struct ConfigRequest
            {
                varstring name;
                varstring value = null;
                varuint32 taggedFields;
            }

            struct ResourceRequestPart2
            {
                varuint32 taggedFields;
            }

            struct AlterConfigsRequestPart2
            {
                uint8 validate_only;
                varuint32 taggedFields;
            }

            struct AlterConfigsResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n resourceCount;
            }

            struct ResourceResponse
            {
                int16 error;
                varstring message = null;
                uint8 type;
                varstring name;
                varuint32 taggedFields;
            }

            struct AlterConfigsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        // Flexible (compact strings/arrays + tagged fields) counterpart of scope config's
        // DescribeConfigs request/response, used only by the generic api envelope
        // (KafkaApiRequestBeginEx/KafkaApiResponseBeginEx) path, mirroring create_topics/
        // delete_topics' use of the first flexible version of their respective APIs rather than
        // the older non-flexible version scope config targets. A null (rather than empty)
        // configNamesCount requests every config for the resource; encoded as varuint32n value -1.
        scope describe_configs_v4
        {
            struct DescribeConfigsRequest // v4
            {
                varuint32 taggedFields;
                varuint32n resourceCount;
            }

            struct ResourceRequest
            {
                uint8 type;
                varstring name;
                varuint32n configNamesCount;
            }

            struct ResourceRequestPart2
            {
                varuint32 taggedFields;
            }

            struct DescribeConfigsRequestPart2
            {
                uint8 includeSynonyms;
                uint8 includeDocumentation;
                varuint32 taggedFields;
            }

            struct DescribeConfigsResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n resourceCount;
            }

            struct ResourceResponse
            {
                int16 error;
                varstring message = null;
                uint8 type;
                varstring name;
                varuint32n configCount;
            }

            struct ConfigResponse
            {
                varstring name;
                varstring value = null;
                uint8 readOnly;
                int8 configSource;
                uint8 isSensitive;
                varuint32n synonymCount;
            }

            struct SynonymResponse
            {
                varstring name;
                varstring value = null;
                int8 source;
                varuint32 taggedFields;
            }

            struct ConfigResponsePart2
            {
                int8 configType;
                varstring documentation = null;
                varuint32 taggedFields;
            }

            struct ResourceResponsePart2
            {
                varuint32 taggedFields;
            }

            struct DescribeConfigsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        // Flexible (compact strings/arrays + tagged fields) OffsetFetch, targeting the earliest
        // flexible version (v6, per the Kafka protocol spec), used only by the generic api envelope
        // (KafkaApiRequestBeginEx/KafkaApiResponseBeginEx) path. A null (rather than empty)
        // topicCount requests committed offsets for every topic the group has, encoded as
        // varuint32n value -1, mirroring describe_configs_v4's null configNamesCount.
        scope offset_fetch_v6
        {
            struct OffsetFetchRequest // v6
            {
                varuint32 taggedFields;
                varstring groupId;
                varuint32n topicCount;
            }

            struct TopicRequest
            {
                varstring name;
                varuint32n partitionCount;
            }

            struct PartitionRequest
            {
                int32 partitionIndex;
            }

            struct TopicRequestPart2
            {
                varuint32 taggedFields;
            }

            struct OffsetFetchRequestPart2
            {
                varuint32 taggedFields;
            }

            struct OffsetFetchResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n topicCount;
            }

            struct TopicResponse
            {
                varstring name;
                varuint32n partitionCount;
            }

            struct PartitionResponse
            {
                int32 partitionIndex;
                int64 committedOffset;
                int32 committedLeaderEpoch = -1;
                varstring metadata = null;
                int16 errorCode;
                varuint32 taggedFields;
            }

            struct TopicResponsePart2
            {
                varuint32 taggedFields;
            }

            struct OffsetFetchResponsePart2
            {
                int16 errorCode;
                varuint32 taggedFields;
            }
        }

        // Flexible (compact strings/arrays + tagged fields) ListOffsets, targeting the earliest
        // flexible version (v6, per the Kafka protocol spec), used only by the generic api envelope
        // (KafkaApiRequestBeginEx/KafkaApiResponseBeginEx) path. No list_offsets scope exists
        // elsewhere in this file; scope offsets (non-flexible v2) is a distinct, legacy mechanism
        // used only by KafkaClientFetchFactory.
        scope list_offsets_v6
        {
            struct ListOffsetsRequest // v6
            {
                varuint32 taggedFields;
                int32 replicaId = -1;
                int8 isolationLevel;
                varuint32n topicCount;
            }

            struct TopicRequest
            {
                varstring name;
                varuint32n partitionCount;
            }

            struct PartitionRequest
            {
                int32 partitionIndex;
                int32 currentLeaderEpoch = -1;
                int64 timestamp;
                varuint32 taggedFields;
            }

            struct TopicRequestPart2
            {
                varuint32 taggedFields;
            }

            struct ListOffsetsRequestPart2
            {
                varuint32 taggedFields;
            }

            struct ListOffsetsResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n topicCount;
            }

            struct TopicResponse
            {
                varstring name;
                varuint32n partitionCount;
            }

            struct PartitionResponse
            {
                int32 partitionIndex;
                int16 errorCode;
                int64 timestamp = -1;
                int64 endOffset = -1;
                int32 leaderEpoch = -1;
                varuint32 taggedFields;
            }

            struct TopicResponsePart2
            {
                varuint32 taggedFields;
            }

            struct ListOffsetsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        // Flexible (compact strings/arrays + tagged fields) DescribeAcls v2, used only by the generic
        // api envelope (KafkaApiRequestBeginEx/KafkaApiResponseBeginEx) path, mirroring
        // alter_configs_v2/describe_configs_v4's use of each API's first flexible version. Unlike
        // configs, DescribeAcls has a single filter (no repeated top-level request array); the
        // response nests a variable-length Acls array per resource, mirroring describe_configs_v4's
        // per-resource Config nesting.
        scope describe_acls_v2
        {
            struct DescribeAclsRequest // v2
            {
                varuint32 taggedFields;
                uint8 resourceTypeFilter;
                varstring resourceNameFilter = null;
                uint8 patternTypeFilter;
                varstring principalFilter = null;
                varstring hostFilter = null;
                uint8 operation;
                uint8 permissionType;
            }

            struct DescribeAclsRequestPart2
            {
                varuint32 taggedFields;
            }

            struct DescribeAclsResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                int16 error;
                varstring message = null;
                varuint32n resourceCount;
            }

            struct ResourceResponse
            {
                uint8 type;
                varstring name;
                uint8 patternType;
                varuint32n aclCount;
            }

            struct AclResponse
            {
                varstring principal;
                varstring host;
                uint8 operation;
                uint8 permissionType;
                varuint32 taggedFields;
            }

            struct ResourceResponsePart2
            {
                varuint32 taggedFields;
            }

            struct DescribeAclsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        // Flexible (compact strings/arrays + tagged fields) CreateAcls v2, used only by the generic
        // api envelope (KafkaApiRequestBeginEx/KafkaApiResponseBeginEx) path, mirroring
        // alter_configs_v2's use of the first flexible AlterConfigs version. Each ACL creation is a
        // flat entry (no nested array), so - unlike a resource's nested configs - a creation entry's
        // own trailing tagged fields close the entry directly rather than needing a separate Part2
        // struct.
        scope create_acls_v2
        {
            struct CreateAclsRequest // v2
            {
                varuint32 taggedFields;
                varuint32n creationCount;
            }

            struct AclCreationRequest
            {
                uint8 resourceType;
                varstring resourceName;
                uint8 resourcePatternType;
                varstring principal;
                varstring host;
                uint8 operation;
                uint8 permissionType;
                varuint32 taggedFields;
            }

            struct CreateAclsRequestPart2
            {
                varuint32 taggedFields;
            }

            struct CreateAclsResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n resultCount;
            }

            struct AclCreationResultResponse
            {
                int16 error;
                varstring message = null;
                varuint32 taggedFields;
            }

            struct CreateAclsResponsePart2
            {
                varuint32 taggedFields;
            }
        }

        // Flexible (compact strings/arrays + tagged fields) DeleteAcls v2, used only by the generic
        // api envelope (KafkaApiRequestBeginEx/KafkaApiResponseBeginEx) path, mirroring
        // describe_configs_v4's use of the first flexible DescribeConfigs version. Each filter is a
        // flat request entry (own trailing tagged fields close it directly, like create_acls_v2's
        // AclCreationRequest), but the response nests a variable-length MatchingAcls array per filter
        // result, mirroring describe_configs_v4's per-resource Config nesting.
        scope delete_acls_v2
        {
            struct DeleteAclsRequest // v2
            {
                varuint32 taggedFields;
                varuint32n filterCount;
            }

            struct DeleteAclsFilterRequest
            {
                uint8 resourceTypeFilter;
                varstring resourceNameFilter = null;
                uint8 patternTypeFilter;
                varstring principalFilter = null;
                varstring hostFilter = null;
                uint8 operation;
                uint8 permissionType;
                varuint32 taggedFields;
            }

            struct DeleteAclsRequestPart2
            {
                varuint32 taggedFields;
            }

            struct DeleteAclsResponse
            {
                varuint32 taggedFields;
                int32 throttleTimeMillis;
                varuint32n filterResultCount;
            }

            struct FilterResultResponse
            {
                int16 error;
                varstring message = null;
                varuint32n matchingAclCount;
            }

            struct MatchingAclResponse
            {
                int16 error;
                varstring message = null;
                uint8 resourceType;
                varstring resourceName;
                uint8 patternType;
                varstring principal;
                varstring host;
                uint8 operation;
                uint8 permissionType;
                varuint32 taggedFields;
            }

            struct FilterResultResponsePart2
            {
                varuint32 taggedFields;
            }

            struct DeleteAclsResponsePart2
            {
                varuint32 taggedFields;
            }
        }


        scope api_versions
        {
            struct ApiVersionsResponse // v0
            {
                int16 errorCode;
                int32 apiKeyCount;
            }

            struct ApiVersionsResponseKey
            {
                int16 apiKey;
                int16 minVersion;
                int16 maxVersion;
            }
        }

        scope sasl
        {
            struct SaslHandshakeRequest // v1
            {
                string16 mechanism;
            }

            struct SaslHandshakeResponse // v1
            {
                int32 correlationId;
                int16 errorCode;
                int32 mechanismCount;
            }

            struct SaslHandshakeMechanismResponse
            {
                string16 mechanism;
            }

            struct SaslAuthenticateRequest // v1
            {
                int32 authBytesLen;
                octets[authBytesLen] authBytes = null;
            }

            struct SaslAuthenticateResponse // v1
            {
                int32 correlationId;
                int16 errorCode;
                string16 errorMessage;
                int32 authBytesLen;
                octets[authBytesLen] authBytes = null;
                int64 sessionLifetimeMs;
            }
        }

        scope consumer
        {
            struct ConsumerPartition
            {
                int32 partitionId;
            }

            struct ConsumerTopicPartition
            {
                string16 topic;
                int32 partitionCount;
            }

            struct ConsumerSubscriptionUserdata
            {
                uint32 userdataLength;
                octets[userdataLength] userdata;
                int32 ownedPartitions;
            }

            struct ConsumerAssignmentUserdata
            {
                uint32 userdataLength;
                octets[userdataLength] userdata;
            }

            struct ConsumerAssignmentTopicUserdata
            {
                string16 topic;
                uint32 userdataLength;
                octets[userdataLength] userdata;
            }

            struct ConsumerAssignmentTopicsUserdata
            {
                ConsumerAssignmentTopicUserdata[] topicsUserdata;
            }

            struct ConsumerMetadataTopic
            {
                string16 name;
            }

            struct ConsumerSubscriptionMetadata
            {
                int16 version;
                int32 metadataTopicCount;
            }

            struct ConsumerAssignmentMetadata
            {
                int16 version;
                int32 metadataTopicCount;
            }
        }
    }
}
