/*
 * Copyright 2021-2026 Aklivity Inc.
 *
 * Aklivity licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package io.aklivity.zilla.runtime.engine.model;

import io.aklivity.zilla.runtime.common.agrona.buffer.DirectBufferEx;
import io.aklivity.zilla.runtime.common.agrona.buffer.UnsafeBufferEx;

/**
 * Drives a {@link ModelTransform} from the field values a model surfaces once a value has completed, for a
 * model that has no native {@code ModelTransform} adapter of its own yet.
 * <p>
 * Observation-only: a stage sees every field and may accumulate from it, but the model's output bytes
 * have already been generated by the time a field is delivered here, so a {@link FieldEvent#REPLACED} or
 * {@link FieldEvent#DECLINED} answer is discarded rather than written. A model that needs genuine field
 * mutation drives the transform inline instead, as {@code model-avro} does.
 * </p>
 *
 * @see ModelTransform
 */
public final class ModelFieldBridge
{
    private final ModelTransform transform;
    private final Value value;
    private final Control control;
    private final Discard discard;

    public ModelFieldBridge(
        ModelTransform transform)
    {
        this.transform = transform;
        this.value = new Value();
        this.control = new Control();
        this.discard = new Discard();
    }

    /**
     * Delivers {@link FieldEvent#START_VALUE}, opening the field run for one value.
     */
    public void start()
    {
        value.wrap(null, null, 0, 0);
        transform.transform(control, value, FieldEvent.START_VALUE, discard);
    }

    /**
     * Delivers one {@link FieldEvent#FIELD}. The buffer slice is valid only for the duration of the call.
     *
     * @param path    the path the field was found at
     * @param buffer  the buffer containing the field value
     * @param index   the offset of the field value
     * @param length  the length of the field value
     */
    public void field(
        String path,
        DirectBufferEx buffer,
        int index,
        int length)
    {
        value.wrap(path, buffer, index, length);
        transform.transform(control, value, FieldEvent.FIELD, discard);
    }

    /**
     * Flushes the chain and delivers {@link FieldEvent#END_VALUE}, closing the field run for one value.
     */
    public void end()
    {
        value.wrap(null, null, 0, 0);
        transform.flush(control, value, discard);
        transform.transform(control, value, FieldEvent.END_VALUE, discard);
    }

    private static final class Value implements ModelSource
    {
        private static final byte[] EMPTY = new byte[0];

        private final UnsafeBufferEx view;

        private String path;

        private Value()
        {
            this.view = new UnsafeBufferEx(EMPTY);
        }

        @Override
        public String getPath()
        {
            return path;
        }

        @Override
        public DirectBufferEx getValue()
        {
            return view;
        }

        private void wrap(
            String path,
            DirectBufferEx buffer,
            int index,
            int length)
        {
            this.path = path;
            if (buffer != null)
            {
                view.wrap(buffer, index, length);
            }
            else
            {
                view.wrap(EMPTY);
            }
        }
    }

    // observation-only: there is no output left to reject into by the time a field is delivered here
    private static final class Control implements ModelController
    {
        @Override
        public void reject(
            String diagnostic)
        {
        }
    }

    private static final class Discard implements ModelSink
    {
        @Override
        public FieldStatus transform(
            ModelController control,
            ModelSource source,
            FieldEvent event)
        {
            return FieldStatus.ADVANCED;
        }

        @Override
        public boolean identity()
        {
            return true;
        }
    }
}
