#
# Copyright 2021-2024 Aklivity Inc
#
# Licensed under the Aklivity Community License (the "License"); you may not use
# this file except in compliance with the License.  You may obtain a copy of the
# License at
#
#   https://www.aklivity.io/aklivity-community-license/
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OF ANY KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations under the License.
#

---
name: test
telemetry:
    attributes:
        service.namespace: example
        service.name: zilla
    metrics:
        - test.counter
        - test.gauge
    exporters:
        test0:
            type: otlp
            options:
                interval: 1
                signals:
                    - metrics
                endpoint:
                    location: http://localhost:4318
                    overrides:
                        metrics: /v1/metrics
bindings:
    net0:
        type: test
        kind: server
        options:
            metrics:
                - name: test.counter
                  kind: counter
                  values:
                      - 42
                      - 21
                      - 14
                - name: test.gauge
                  kind: gauge
                  values:
                      - 11
                      - 22
                      - 33
        exit: app0
        telemetry:
            metrics:
                - test.*
