image:
  tag: develop-SNAPSHOT

args: ["start", "-v", "-e"]

env:
  - name: TCP_CLIENT_HOST
    value: mosquitto
  - name: TCP_CLIENT_PORT
    value: '"1883"'

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7183
      name: mqtt
