env:
  MOSQUITTO_BROKER_HOST: mosquitto
  MOSQUITTO_BROKER_PORT: "1883"
  ZILLA_INCUBATOR_ENABLED: "true"
  JAVA_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7183
      name: mqtt
    - port: 5005
      name: debug
