image:
  tag: develop-SNAPSHOT

args: ["start", "-v", "-e"]

extraEnv:
  - name: MOSQUITTO_BROKER_HOST
    value: mosquitto
  - name: MOSQUITTO_BROKER_PORT
    value: "1883"

livenessProbePort: 7183
readinessProbePort: 7183

service:
  ports:
    - port: 7183
      name: mqtt
