replicaCount: 1

image:
  registry: ghcr.io
  repository: vordimous/mqtt-simulator
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "zilla-quickstart"

brokerUrl: "broker.svc.cluster.local"
brokerPort: 1883

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

## Annotations to be added to the Deployment
##
annotations: {}

resources: {}
  # limits:
  #   cpu: 200m
  #   memory: 512Mi
  # requests:
  #   cpu: 200m
  #   memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

env: {}

initContainers: {}

volumeMounts: {}

volumes: {}
