replicaCount: 1

image:
  repository: ghcr.io/aklivity/zilla
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

livenessProbePort: 0
readinessProbePort: 0

tls:
  enabled: false
  keystorePath: ""
  keystoreLocalPath: ""
  keystorePassword: ""

service:
  type: ClusterIP
  port: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

zilla_yaml: |
  name: example
