livenessProbePort: 8080
readinessProbePort: 8080

service:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: https

tls:
  enabled: true
  keystore:
    name: localhost.p12
    localPath: examples/ws.echo/localhost.p12
    mountPath: tls
    password: generated

verify: |
  $ wscat -c ws://localhost:8080/ -s echo
  Connected (press CTRL+C to quit)
  > Hello, world
  < Hello, world

  $ wscat -c wss://localhost:9090/ --ca examples/ws.echo/test-ca.crt -s echo
  Connected (press CTRL+C to quit)
  > Hello, world
  < Hello, world
