livenessProbePort: 8080
readinessProbePort: 8080

service:
  ports:
    - port: 8080
      name: http
    - port: 9090
      name: https

secrets:
  - name: tls
    mountPath: tls
    localPath: examples/ws.echo/tls/*

keystorePassword: generated
