version: "3"

networks:
  net0:
    driver: overlay

services:

  zilla:
    image: "ghcr.io/aklivity/zilla:latest"
    hostname: "zilla"
    command: [ "start", "-v", "-e" ]
    volumes:
      - ./conf:/etc/zilla:ro
    networks:
      - net0
    ports:
      - "8080:8080"
      - "9090:9090"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: "zookeeper"
    networks:
      - net0
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:3.1.0"
    hostname: "kafka.internal.net"
    networks:
      - net0
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT,ZILLA:SASL_PLAINTEXT
      - KAFKA_CFG_LOG_DIRS=/tmp/logs
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,INTERNAL://:29092,ZILLA://:29091
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,INTERNAL://kafka.internal.net:29092,ZILLA://kafka.internal.net:29091
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-256
    depends_on:
      - zookeeper
    volumes:
      - ./kafka/kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
    ports:
      - "9092:9092"
