apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-adapter
  labels:
    app.kubernetes.io/instance: prometheus-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-adapter
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: prometheus-adapter
    spec:
      containers:
        - name: prometheus-adapter
          image: "registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.10.0"
          args:
            - /adapter
            - --secure-port=443
            - --cert-dir=/tmp/cert
            - --logtostderr=true
            - --prometheus-url=http://prometheus.zilla-kubernetes-prometheus-autoscale.svc.cluster.local:9090
            - --metrics-relist-interval=1m
            - --v=4
            - --config=/etc/prometheus-adapter/config.yaml
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
              - name: config
                mountPath: /etc/prometheus-adapter/
                readOnly: true
              - mountPath: /tmp
                name: tmp
      serviceAccountName: prometheus-adapter
      volumes:
        - name: config
          configMap:
            name: prometheus-adapter
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter
data:
  config.yaml: |-
{{ .Files.Get "files/prometheus-adapter.yaml" | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-adapter
spec:
  selector:
    app.kubernetes.io/instance: prometheus-adapter
  ports:
    - name: https
      port: 443
      targetPort: https
  type: ClusterIP
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: prometheus-adapter
    namespace: zilla-kubernetes-prometheus-autoscale
    port: 443
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-adapter
  labels:
    app.kubernetes.io/instance: prometheus-adapter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-adapter-resource-reader
  labels:
    app.kubernetes.io/instance: prometheus-adapter
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - services
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: prometheus-adapter
  name: prometheus-adapter-server-resources
rules:
  - apiGroups:
      - custom.metrics.k8s.io
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-adapter-auth-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/instance: prometheus-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: prometheus-adapter
    namespace: zilla-kubernetes-prometheus-autoscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-adapter-system-auth-delegator
  labels:
    app.kubernetes.io/instance: prometheus-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: prometheus-adapter
    namespace: zilla-kubernetes-prometheus-autoscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-adapter-resource-reader
  labels:
    app.kubernetes.io/instance: prometheus-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-adapter-resource-reader
subjects:
  - kind: ServiceAccount
    name: prometheus-adapter
    namespace: zilla-kubernetes-prometheus-autoscale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-adapter-hpa-controller
  labels:
    app.kubernetes.io/instance: prometheus-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-adapter-server-resources
subjects:
  - kind: ServiceAccount
    name: prometheus-adapter
    namespace: zilla-kubernetes-prometheus-autoscale
