name: ${NAMESPACE:-zilla-asyncapi-sse-proxy}
services:
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION:-latest}
    restart: unless-stopped
    hostname: zilla.examples.dev
    ports:
      - 7114:7114
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: ["CMD", "bash", "-c", "echo -n '' > /dev/tcp/127.0.0.1/7114"]
    environment:
      SSE_SERVER_HOST: sse-server
      SSE_SERVER_PORT: 8001
    volumes:
      - ./etc:/etc/zilla
      - ./sse-asyncapi.yaml:/etc/zilla/specs/sse-asyncapi.yaml
    command: start -v -e

  sse-server:
    image: ghcr.io/aklivity/extras-sse-server:sha-42ad67e
    restart: unless-stopped
    ports:
      - 8001:8001
      - 7001:7001
    stdin_open: true
    tty: true
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 5
      test: netstat -an | grep 8001 > /dev/null; if [ 0 != $? ]; then exit 1; fi;
    command: -v -p 8001 -i 7001

networks:
  default:
    driver: bridge
