env:
  SSE_SERVER_HOST: sse-server
  SSE_SERVER_PORT: "8001"
  KEYSTORE_PASSWORD: generated
  ZILLA_INCUBATOR_ENABLED: "true"

livenessProbePort: 7114
readinessProbePort: 7114

service:
  ports:
    - port: 7114
      name: http
