apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args: ["start", "-v", "-e"]
          env:
          {{- if .Values.tls.enabled }}
            - name: KEYSTORE_PASSWORD
              value: {{ .Values.tls.keystorePassword }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $port := .Values.service.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.port }}
              protocol: TCP
          {{- end}}
          {{- if .Values.livenessProbePort }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.livenessProbePort }}
          {{- end}}
          {{- if .Values.readinessProbePort }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.readinessProbePort }}
          {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/zilla
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: /etc/zilla/tls
            {{- end }}
            {{- if .Values.filesToConfigMap.enabled }}
            - name: {{ .Values.filesToConfigMap.name }}
              mountPath: {{ .Values.filesToConfigMap.mountPath }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: zilla
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: tls
            items:
              - key: {{ .Values.tls.keystorePath }}
                path: {{ .Values.tls.keystorePath }}
        {{- end }}
        {{- if .Values.filesToConfigMap.enabled }}
        - name: {{ .Values.filesToConfigMap.name }}
          configMap:
            name: {{ .Values.filesToConfigMap.name }}
        {{- end }}
