{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: tls
type: Opaque
data:
  {{ .Values.tls.keystorePath }}: {{ .Files.Get .Values.tls.keystoreLocalPath | b64enc }}
{{- end }}
