apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilla
  labels:
    app.kubernetes.io/instance: zilla
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zilla
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zilla
    spec:
      containers:
        - name: zilla
          image: "ghcr.io/aklivity/zilla:latest"
          args: ["start", "-v", "-e"]
          ports:
            - containerPort: 12345
          readinessProbe:
            tcpSocket:
              port: 12345
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: config
              mountPath: /etc/zilla
      volumes:
        - name: config
          configMap:
            name: zilla
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zilla
data:
  zilla.yaml: |-
{{ .Files.Get "files/zilla.yaml" | indent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: zilla
spec:
  selector:
    app.kubernetes.io/instance: zilla
  ports:
    - name: tcp
      port: 12345
  type: ClusterIP
