extraEnv:
  - name: ZILLA_INCUBATOR_ENABLED
    value: "true"

livenessProbePort: 7114
readinessProbePort: 7114

args: ["start", "-v", "-e", "-Pzilla.binding.kafka.client.produce.record.framing.size=1024"]

service:
  ports:
    - port: 7114
      name: http
