name: Examples test Checker

on:
  push:
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 22
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/io/aklivity/zilla
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: ./mvnw -B -U -nsu -Ddocker.logStdout -Ddocker.verbose -DskipTests install jacoco:report-aggregate
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: Create container tar
        run: docker save ghcr.io/aklivity/zilla:develop-SNAPSHOT > /tmp/zilla.tar
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zilla-image
          path: /tmp/zilla.tar

  test-openapi-proxy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zilla-image
          path: /tmp
      
      - name: Load image
        run: |
          docker load --input /tmp/zilla.tar
          docker image ls -a

      - name: Checkout docs repo
        uses: actions/checkout@v4
        with:
          repository: aklivity/zilla-examples
          ref: refs/heads/example-startup-compose

      - name: Startup
        run: ./startup.sh openapi.proxy

      - name: Execute Test
        working-directory: openapi.proxy
        run: |
          set -o pipefail
          ./test.sh | tee $GITHUB_STEP_SUMMARY
