name: Link Checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2.3.0
        with:
          fail: true
          args: --exclude-mail --exclude .+localhost.+ README.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
